### ISSUE TITLE
One missing data pair for tuebingen

### ISSUE THREAD

**Issue by zhangtj1996** [FenTechSolutions/CausalDiscoveryToolbox#113]
Hi there,

I found there is one dataset missing when I load the tuebingen dataset. The total number should be 100 instead of 99 for version 1.0 in https://webdav.tuebingen.mpg.de/cause-effect/.

Could anybody have a check and update the dataset?

Best wishes.

**Comment by Diviyan-Kalainathan** [comment]
Hello ! 
It's not *really* a mistake : there is actually one multivariate pair in the Tuebingen dataset  which format  is not managed by most algorithms. Thus this pair has been knowingly ignored... :roll_eyes: 

Best regards,
Diviyan

**Comment by zhangtj1996** [comment]
Thank you very much, then this issue could be closed.

**Comment by Diviyan-Kalainathan** [comment]
Great !

**Comment by amir-rahnama** [comment]
There are 108 pairs of datasets in Tuebingen datasets, not 100.  It is impossible to know which one is included in your dataset since you have started to call them differently than the original pairs (pair1 instead of pair0001). 

In addition, you have reversed all the X and Ys so that all targets are now  1 (X causes Y). This makes it impossible to use AUC, for example, to measure the performance of these datasets. 

I think updating the dataset with the right key from the original dataset, plus not reverting the columns but keeping the target as 0 will make your dataset much more useful.
